name: AWS Code Deploy Release

on:
  workflow_dispatch
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - id: GetBuildVersion
      run: |
        $version="1.0.0"
        echo "release_version=${version}" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Dump github context
      run:   
        echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Output
      run:  |
        echo "REPO_VAR=${{ env.REPO_NAME }}"
        echo "${{ env.release_version }}" 
