name: AWS Code Deploy Release

on:
  workflow_dispatch
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - id: GetBuildVersion
      run: |
        $version = "1.0.0"
        echo "::set-env name=version::${version}"
      shell: pwsh
    - name: Dump github context
      run:   echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Output
      run:  |
        echo "REPO_NAME=${{ github.event.repository.name }}"
