name: AWS Code Deploy Release

on:
  workflow_dispatch
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::080007128336:role/voice/gh-deploy/dev/appGHDeployRoleDEV
        aws-region: eu-west-1
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      env:
        GITHUB_ACTOR: "Marlon"
      with:
        role-to-assume: arn:aws:iam::080007128336:role/voice/gh-deploy/dev/appGHDeployChainedRoleDEV
        role-session-name: AssumedRole
        aws-region: eu-west-1
        role-chaining: true
        
